# DEV SERVER PORT
server:
  port: 8082

# DATABASE CONFIGURATION
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_app
    username: root
    password: Santhu@7022

#    hikari:
#      pool-name: HikariCP
#      maximum-pool-size: 5
#      connection-timeout: 10000
#      idle-timeout: 600000
#      max-lifetime: 1800000
#      validation-timeout: 1800000
#      initialization-fail-timeout: -1

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
#    show-sql: true

logging:
  level:
    org.springframework.security: DEBUG

security:
  jwt:
#    secret: "${JWT_SECRET:ZmFrZS1qd3Qtc2VjcmV0LWtleS0yNTYtYml0LXN1cGVyLXNlY3VyZQ==}"
    secret: "${JWT_SECRET:3dPDmULOGcbB71hEZK4XBWKFN+yY3kuVjBVwGMbBYx14oghXb50aCxRdMDM2+gBR6kWhxelq7lEx16tSrkdBVg==}"
    issuer: ${JWT_ISSUER:substring-auth-app}
    access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:3600}
    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:86400}
    refresh-token-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}
    cookie-secure: ${JWT_COOKIE_SECURE:true}
    cookie-http-only: ${JWT_HTTP_COOKIE_ONLY:true}
    cookie-same-site: ${JWT_COOKIE_SAME_SITE:true}

